# Generated by Django 3.1.6 on 2021-03-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
