# Generated by Django 3.1.6 on 2021-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20210302_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_of_completion',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Дата выполнения'),
        ),
    ]
